apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: no-catalog-repo
  annotations:
    github.com/project-slug: mbocek-vw/no-catalog-repo
spec:
  type: other
  lifecycle: unknown
  owner: guests
